language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

before_script:
 - npm install
 - npm install -g firebase-tools

script:
  - npm run build
  - firebase deploy --token $FIREBASE_DEPLOY_KEY
