language: node_js
node_js:
  - 8

cache:
  directories:
    - node_modules

before_script:
 - npm install
 - npm install -g firebase-tools

script:
  - npm run build
  - node_modules/.bin/eslint --fix "./src/**"
  - firebase deploy --token $FIREBASE_DEPLOY_KEY
